name: paymant_ui
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.4
  mask_text_input_formatter: ^2.9.0
  credit_card_scanner: ^1.0.5
  shared_preferences: ^2.2.2


  path_provider: ^2.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

flutter:

  uses-material-design: true


  assets:
    - assets/images/
